// <auto-generated />
using CHNU_Connect.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CHNU_Connect.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260526120000_AddActivityLog")]
    partial class AddActivityLog
    {
    }
}
