// <auto-generated />
using CHNU_Connect.DAL.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;

#nullable disable

namespace CHNU_Connect.DAL.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20260523120000_AddBodyToNotification")]
    partial class AddBodyToNotification
    {
    }
}
